name: freezed_union_example
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.8.0
  freezed_annotation: ^0.14.2

dev_dependencies:
  pedantic: ^1.10.0
  build_runner: ^2.0.4
  freezed: ^0.14.2
